version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - shanejonas
  - BelfordZ
  assignees:
  - shanejonas
  - BelfordZ
  ignore:
  - dependency-name: "@open-rpc/meta-schema"
    versions:
    - ">= 1.4.a, < 1.5"
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.23
    - 14.14.24
    - 14.14.25
    - 14.14.26
    - 14.14.27
    - 14.14.28
    - 14.14.29
    - 14.14.30
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: "@open-rpc/docs-react"
    versions:
    - 1.2.6
    - 1.3.0
    - 1.4.0
    - 1.4.1
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.0
    - 17.0.1
    - 17.0.2
  - dependency-name: "@types/react"
    versions:
    - 17.0.0
    - 17.0.1
    - 17.0.2
    - 17.0.3
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
